# Generated by Django 6.0.5 on 2026-10-02 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_enrollment_estado'),
        ('quizzes', '0004_quiz_hash_verificado_quiz_verificado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='sources/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('PPTX', 'PPTX'), ('TXT', 'TXT')], max_length=4)),
                ('texto_extraido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='courses.course')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametros', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=12)),
                ('mensaje', models.TextField(blank=True)),
                ('preguntas_solicitadas', models.PositiveSmallIntegerField(default=5)),
                ('preguntas_generadas', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_generation_jobs', to='courses.course')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='quizzes.quiz')),
                ('documentos', models.ManyToManyField(related_name='generation_jobs', to='quiz_generation.sourcedocument')),
            ],
        ),
    ]
