# Generated by Django 5.2.6 on 2026-05-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='quizzes/questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='explicacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explicacion_imagen',
            field=models.FileField(blank=True, null=True, upload_to='quizzes/question_explanations/'),
        ),
    ]
