# Generated by Django 6.0.5 on 2026-10-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_media_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='tiempo_por_pregunta',
        ),
    ]
