# Generated by Django 6.0.5 on 2026-10-02 02:43

import django.db.models.deletion
import hashlib
import json
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def verify_existing_quizzes(apps, schema_editor):
    Quiz = apps.get_model('quizzes', 'Quiz')
    Question = apps.get_model('quizzes', 'Question')
    Option = apps.get_model('quizzes', 'Option')
    for quiz in Quiz.objects.all():
        content = []
        for question in Question.objects.filter(quiz=quiz).order_by('orden'):
            content.append({
                'orden': question.orden,
                'enunciado': question.enunciado,
                'opciones': [
                    {'letra': option.letra, 'texto': option.texto, 'es_correcta': option.es_correcta}
                    for option in Option.objects.filter(question=question).order_by('letra')
                ],
            })
        payload = json.dumps(content, ensure_ascii=True, sort_keys=True, separators=(',', ':')).encode()
        quiz.hash_verificado = hashlib.sha256(payload).hexdigest()
        quiz.verificado_en = timezone.now()
        quiz.save(update_fields=['hash_verificado', 'verificado_en'])


def unverify_existing_quizzes(apps, schema_editor):
    apps.get_model('quizzes', 'Quiz').objects.update(hash_verificado=None, verificado_en=None)


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quiz_tiempo_por_pregunta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hash_verificado',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='verificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TeacherVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('correctas', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('hash_contenido', models.CharField(max_length=64)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_verification_attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherVerificationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_marcada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.teacherverificationattempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_teacher_verification_answer')],
            },
        ),
        migrations.RunPython(verify_existing_quizzes, unverify_existing_quizzes),
    ]
