# Generated by Django 5.2.6 on 2026-03-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveanswer',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
