# Generated by Django 5.2.6 on 2026-03-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_liveanswer_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='mostrando_resultados',
            field=models.BooleanField(default=False),
        ),
    ]
