# Generated by Django 5.2.6 on 2026-05-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_quizsession_mostrando_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='pausa_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='tiempo_pausa_acumulado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='estado',
            field=models.CharField(choices=[('ESPERA', 'En espera'), ('EN_CURSO', 'En curso'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='ESPERA', max_length=15),
        ),
    ]