# Generated by Django 6.0.5 on 2026-10-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0004_quizsession_pause_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveAnswer',
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
        migrations.DeleteModel(
            name='SessionParticipant',
        ),
    ]
