# Generated by Django 6.0.5 on 2026-10-02 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0002_question_media_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('NORMAL', 'Normal')], default='NORMAL', max_length=10)),
                ('abre_en', models.DateTimeField()),
                ('cierra_en', models.DateTimeField()),
                ('intentos_permitidos', models.PositiveSmallIntegerField(default=1)),
                ('tiempo_limite_minutos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mostrar_respuestas', models.CharField(choices=[('AL_ENVIAR', 'Al enviar'), ('AL_CIERRE', 'Al cierre'), ('NUNCA', 'Nunca')], default='AL_CIERRE', max_length=12)),
                ('cerrada_manualmente', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('limite_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('ENVIADO', 'Enviado')], default='EN_PROGRESO', max_length=12)),
                ('enviado_automaticamente', models.BooleanField(default=False)),
                ('correctas', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hash_contenido', models.CharField(max_length=64)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='evaluaciones.asignacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('respondida_en', models.DateTimeField(auto_now=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.intento')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_intento', to='quizzes.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_intento', to='quizzes.question')),
            ],
        ),
        migrations.AddConstraint(
            model_name='intento',
            constraint=models.UniqueConstraint(fields=('asignacion', 'estudiante', 'numero'), name='unique_intento_por_estudiante'),
        ),
        migrations.AddConstraint(
            model_name='respuestaintento',
            constraint=models.UniqueConstraint(fields=('intento', 'question'), name='unique_respuesta_por_pregunta'),
        ),
    ]
